const fs = require('fs');
let content = fs.readFileSync('src/components/layout/Navbar.tsx', 'utf8');

const regex = /const navLinks = isDashboard[\s\S]*?\{ name: t\("navbar\.discover"\), path: "\/discovery" \},\r?\n\s*\];/;

const newNavLinks = "  const userRole = user?.role?.toUpperCase();\n\n  const navLinks = userRole === 'ADMIN'\n    ? [\n        { name: 'Profile', path: '/dashboard?tab=profile' },\n        { name: 'Settings', path: '/dashboard?tab=settings' },\n      ]\n    : isDashboard \n      ? userRole === 'GUIDE'\n        ? [\n            { name: t('navbar.dashboard'), path: '/dashboard' },\n            { name: 'My Tours', path: '/dashboard?tab=tours' },\n            { name: t('navbar.profile'), path: '/dashboard?tab=profile' },\n            { name: t('navbar.bookings'), path: '/dashboard?tab=bookings' },\n            { name: 'Settings', path: '/dashboard?tab=settings' },\n          ]\n        : userRole === 'TRAVELLER'\n          ? [\n              { name: t('navbar.dashboard'), path: '/dashboard' },\n              { name: 'Book Stays', path: '/resorts' },\n              { name: t('navbar.wishlist'), path: '/dashboard/wishlist' },\n              { name: t('navbar.bookings'), path: '/dashboard/bookings' },\n              { name: 'Notifications', path: '/dashboard/notifications' },\n              { name: t('navbar.profile'), path: '/dashboard/profile' },\n            ]\n          : [\n              { name: t('navbar.dashboard'), path: '/dashboard' },\n              { name: 'Properties', path: '/dashboard?tab=properties' },\n              { name: t('navbar.bookings'), path: '/dashboard?tab=bookings' },\n              { name: t('navbar.profile'), path: '/dashboard/profile' },\n              { name: 'Settings', path: '/dashboard?tab=settings' },\n            ]\n      : [\n          { name: t('navbar.resorts'), path: '/resorts' },\n          { name: t('navbar.discover'), path: '/discovery' },\n        ];";

content = content.replace(regex, JSON.parse(newNavLinks));
fs.writeFileSync('src/components/layout/Navbar.tsx', content);
