const fs = require('fs');
let code = fs.readFileSync('c:/Users/sanju/Desktop/Hampi-Stays/frontend/src/pages/admin/AdminDashboard.tsx', 'utf8');

code = code.replace(/import \{ Select \} from "\.\.\/\.\.\/components\/ui\/Select";/, 
  'import { Select } from "../../components/ui/Select";\nimport { jsPDF } from "jspdf";\nimport html2canvas from "html2canvas";');

code = code.replace(/const \[activeTab, setActiveTab\] = useState\<AdminTab\>\("overview"\);/, 
  'const [activeTab, setActiveTab] = useState<AdminTab>("overview");\n  const [isExportingPDF, setIsExportingPDF] = useState(false);\n\n  const exportToPDF = async () => {\n    setIsExportingPDF(true);\n    const toastId = toast.loading("Generating High-Resolution PDF...");\n    try {\n      const element = document.getElementById("overview-report-content");\n      if (!element) throw new Error("Content not found");\n      const canvas = await html2canvas(element, { scale: 2, useCORS: true, logging: false, backgroundColor: "#FDFBF7" });\n      const imgData = canvas.toDataURL("image/png");\n      const pdf = new jsPDF("p", "mm", "a4");\n      const pdfWidth = pdf.internal.pageSize.getWidth();\n      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;\n      let heightLeft = pdfHeight;\n      let position = 0;\n      pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);\n      heightLeft -= pdf.internal.pageSize.getHeight();\n      while (heightLeft >= 0) {\n        position = heightLeft - pdfHeight;\n        pdf.addPage();\n        pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);\n        heightLeft -= pdf.internal.pageSize.getHeight();\n      }\n      pdf.save(`HampiStays_Performance_Report_${new Date().toISOString().split("T")[0]}.pdf`);\n      toast.success("Report exported successfully!", { id: toastId });\n    } catch (error) {\n      console.error(error);\n      toast.error("Failed to generate PDF report.", { id: toastId });\n    } finally {\n      setIsExportingPDF(false);\n    }\n  };');

code = code.replace(/const renderOverview = \(\) \=> \(\n\s*<div className="space-y-8">\n\s*\{\/\* Stats Grid \*\/\}/, 
  'const renderOverview = () => (\n  <div className="space-y-8">\n    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-6 rounded-[2rem] border border-sand-200 shadow-sm">\n      <div>\n        <h2 className="text-2xl font-bold text-navy-950">Platform Command Center</h2>\n        <p className="text-sm text-navy-600">Real-time overview of your luxury eco-resort ecosystem.</p>\n      </div>\n      <Button onClick={exportToPDF} disabled={isExportingPDF} className="bg-gold-500 hover:bg-gold-600 text-white rounded-xl shadow-lg hover:shadow-xl flex items-center gap-2">\n        {isExportingPDF ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}\n        Export PDF Report\n      </Button>\n    </div>\n    <div id="overview-report-content" className="space-y-8 p-4 bg-sand-50/50 rounded-[2rem]">\n      {/* Stats Grid */}');

code = code.replace(/<\/motion\.div>\n\s*\)\}\n\s*<\/div>\n\s*<\/div>\n\s*\);/, 
  '</motion.div>\n      )}\n      </div>\n    </div>\n  </div>\n  );');

fs.writeFileSync('c:/Users/sanju/Desktop/Hampi-Stays/frontend/src/pages/admin/AdminDashboard.tsx', code);
